GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJuYW1lIjoiQWd1bmcgSGFyd2luIG4iLCJlbWFpbCI6ImFndW5nQGdtYWlsLmNvbSIsImlhdCI6MTY4NzAwNjMwNywiZXhwIjoxNjg3MDA2MzI3fQ.q-e8kLGqBe4cQYBEsgyugscrxtFfqw56rdK6DTa-HLQ
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Agung Harwin n",
    "email":"agung@gmail.com",
    "password":"12345",
    "confPassword":"12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"agung@gmail.com",
    "password":"12345"
}

###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout